
CREATE DATABASE LIVRARIA_DB_FABY;
USE LIVRARIA_DB_FABY;

CREATE TABLE AUTORES (
    ID_AUTOR INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100)
);

CREATE TABLE LIVROS (
    ID_LIVRO INT PRIMARY KEY AUTO_INCREMENT,
    TITULO VARCHAR(150),
    ID_AUTOR INT,
    FOREIGN KEY (ID_AUTOR) REFERENCES AUTORES(ID_AUTOR)
);

CREATE TABLE VENDAS (
    ID_VENDA INT PRIMARY KEY AUTO_INCREMENT,
    DATA_VENDA DATE
);

CREATE TABLE ITENS_VENDA (
    ID_ITEM INT PRIMARY KEY AUTO_INCREMENT,
    ID_VENDA INT,
    ID_LIVRO INT,
    QUANTIDADE INT,
    FOREIGN KEY (ID_VENDA) REFERENCES VENDAS(ID_VENDA),
    FOREIGN KEY (ID_LIVRO) REFERENCES LIVROS(ID_LIVRO)
);

INSERT INTO AUTORES (NOME) VALUES ('Machado de Assis'), ('George Orwell'), ('J.K. Rowling');

INSERT INTO LIVROS (TITULO, ID_AUTOR)
VALUES ('Dom Casmurro', 1),
       ('A Revolução dos Bichos', 2),
       ('Harry Potter', 3);

INSERT INTO VENDAS (DATA_VENDA) VALUES ('2025-10-19');

INSERT INTO ITENS_VENDA (ID_VENDA, ID_LIVRO, QUANTIDADE)
VALUES (1, 3, 5);  -- Harry Potter vendido 5 vezes





-- DESAFIO AULA 15:

-- Relatório 1:

USE LIVRARIA_DB;

SELECT 
    L.TITULO AS TITULO_DO_LIVRO,
    A.NOME AS NOME_DO_AUTOR
FROM LIVROS L
INNER JOIN AUTORES A ON L.ID_AUTOR = A.ID_AUTOR;
 
-- Relatório 2:

SELECT 
    L.TITULO AS TITULO_DO_LIVRO,
    IV.QUANTIDADE AS QUANTIDADE_VENDIDA
FROM ITENS_VENDA IV
INNER JOIN LIVROS L ON IV.ID_LIVRO = L.ID_LIVRO;


-- Relatório 3:

SELECT 
    L.TITULO AS TITULO_DO_LIVRO,
    A.NOME AS NOME_DO_AUTOR,
    IV.QUANTIDADE AS QUANTIDADE_VENDIDA
FROM ITENS_VENDA IV
INNER JOIN LIVROS L ON IV.ID_LIVRO = L.ID_LIVRO
INNER JOIN AUTORES A ON L.ID_AUTOR = A.ID_AUTOR;


-- Relatório 4:

SELECT 
    L.TITULO AS TITULO_DO_LIVRO,
    SUM(IV.QUANTIDADE) AS QUANTIDADE_TOTAL_VENDIDA
FROM LIVROS L
LEFT JOIN ITENS_VENDA IV ON L.ID_LIVRO = IV.ID_LIVRO
GROUP BY L.TITULO;
