USE ABD_03361_A_FABIANE_AGUILERA;

CREATE TABLE comidas_favoritas (

	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME_PESSOA VARCHAR(100) NOT NULL,
    COMIDA VARCHAR(100) NOT NULL,
    TIPO VARCHAR(50) NOT NULL,
    NOTA INT,
    CIDADE VARCHAR(100)
);

INSERT INTO comidas_favoritas (NOME_PESSOA, COMIDA, TIPO, NOTA, CIDADE) VALUES ( 'Mário', 'Bolo de milho','Doce','9', 'SÃO PAULO'); 
INSERT INTO comidas_favoritas (NOME_PESSOA, COMIDA, TIPO, NOTA, CIDADE) VALUES ( 'Arineide', 'Mousse de Chocolate','Sobremesa','8','SÃO PAULO');
INSERT INTO comidas_favoritas (NOME_PESSOA, COMIDA, TIPO, NOTA, CIDADE) VALUES ( 'Edson', 'Lasanha','Salgado','7','SÃO PAULO'); 
INSERT INTO comidas_favoritas (NOME_PESSOA, COMIDA, TIPO, NOTA, CIDADE) VALUES ( 'Fernanda', 'Salmão','Salgado','10','SÃO PAULO'); 
INSERT INTO comidas_favoritas (NOME_PESSOA, COMIDA, TIPO, NOTA, CIDADE) VALUES ( 'Marcelo', 'Morango','Fruta','9', 'SÃO PAULO'); 

SELECT * FROM comidas_favoritas;

-- 3 SELECIONE TODAS AS COMIDAS COM NOTA MAIOR QUE 8
SELECT * FROM comidas_favoritas WHERE NOTA > 8; 

-- 4 MOSTRE APENAS O NOME DAS PESSOAS E SUAS COMIDAS FAVORITAS DO TIPO DOCE ORDENADAS PELO NOME

SELECT NOME_PESSOA, COMIDA FROM comidas_favoritas WHERE TIPO = 'DOCE' ORDER BY NOME_PESSOA ASC;

-- 5 MOSTRE AS COMIDAS FAVORITAS DE QUEM MORA EM SÃO PAULO OU RIO DE JANEIRO DICA: USE O IN
SELECT NOME_PESSOA, COMIDA, CIDADE FROM comidas_favoritas WHERE  CIDADE IN (' SÃO PAULO' , ' RIO DE JANEIRO' );

-- 6 ATUALIZE A NOTA DE UMA COMIDA ESPECÍFICA PARA 10 DICA: UPDATE NOME_DA_TABELA SET COLUNA = ... WHERE COLUNA = ...

SELECT * FROM comidas_favoritas;
UPDATE comidas_favoritas
SET NOTA = 10
WHERE ID = 5;

-- 7 ATUALIZE O TIPO DE TODAS AS COMIDAS QUE CONTENHAM A PALAVRA PIZZA(MILHO) PARA SALGADO DICA: USE LIKE

SELECT * FROM comidas_favoritas;
SET SQL_SAFE_UPDATES = 0;
UPDATE comidas_favoritas
SET TIPO = 'Salgado'
WHERE COMIDA LIKE '% milho';

-- 8 EXCLUA TODAS AS COMIDAS QUE TENHAM NOTA MENOR QUE 5

DELETE FROM comidas_favoritas WHERE NOTA < 8;


-- DESAFIO
-- 9 MOSTRE O NOME DA PESSOA E A COMIDA FAVORITA ONDE O NOME_TENHA MAIS DE 10 CARACTERES
-- E A NOTA ESTEJA ENTRE 7 E 10 DICA: USE LENGTH() E BETWEEN

SELECT NOME_PESSOA, COMIDA, NOTA FROM comidas_favoritas WHERE  LENGTH('NOME_PESSOA') > 10 AND NOTA BETWEEN 7 AND 10;

GRANT SELECT, INSERT ON comidas_favoritas TO 'professor'@'%';
REVOKE SELECT ON comidas_favoritas FROM 'professor'@'%';

 
