USE ABD_03361_A_FABIANE_AGUILERA_RELATORIO_VENDAS_EMPRESA;

-- Resposta para o Relatório 1 (INNER JOIN):

SELECT 
    C.NOME,
    P.PRODUTO,
    P.QUANTIDADE,
    P.VALOR_UNITARIO
FROM CLIENTES C
INNER JOIN PEDIDOS P
ON C.ID = P.ID_CLIENTE;


-- Resposta para o Relatório 2 (LEFT JOIN):

SELECT 
    C.NOME,
    P.PRODUTO,
    P.QUANTIDADE,
    P.VALOR_UNITARIO
FROM CLIENTES C
LEFT JOIN PEDIDOS P
ON C.ID = P.ID_CLIENTE;

