USE PADARIA;

CREATE TABLE FORNECEDORES (
    ID_FORNECEDOR INT AUTO_INCREMENT PRIMARY KEY,
    ENDERECO VARCHAR(150),
    RESPONSAVEL VARCHAR(100),
    NOME_FANTASIA VARCHAR(100)
);

CREATE TABLE VENDEDORES (
    ID_VENDEDOR INT AUTO_INCREMENT PRIMARY KEY,
    ENDERECO_DO_ESTABELECIMENTO VARCHAR(150),
    PRIORIDADE_DO_VENDEDOR VARCHAR(50),
    QTD_FUNCIONARIO INT
);


CREATE TABLE PRODUTOS (
    ID_PRODUTO INT AUTO_INCREMENT PRIMARY KEY,
    CODIGO_PRODUTO VARCHAR(20),
    DESCRICAO_PRODUTO VARCHAR(100),
    ID_FORNECEDOR INT,
    ID_VENDEDOR INT,
    FOREIGN KEY (ID_FORNECEDOR) REFERENCES FORNECEDOR(ID_FORNECEDOR),
    FOREIGN KEY (ID_VENDEDOR) REFERENCES VENDEDOR(ID_VENDEDOR)
);

INSERT INTO FORNECEDORES (ENDERECO, RESPONSAVEL, NOME_FANTASIA)
VALUES
('RUA DAS FLORES, 123', 'JOÃO SILVA', 'FORNO DE OURO'),
('AV. CENTRAL, 456', 'MARIA LIMA', 'DOCES DA VILA'),
('RUA PADRE JOSÉ, 789', 'CARLOS PEREIRA', 'CAFÉS PREMIUM');

INSERT INTO VENDEDORES (ENDERECO_DO_ESTABELECIMENTO, PRIORIDADE_DO_VENDEDOR, QTD_FUNCIONARIO)
VALUES
('RUA DAS ROSAS, 100', 'ALTA', 5),
('AV. PAULISTA, 200', 'MÉDIA', 3),
('RUA DOS PINHEIROS, 50', 'BAIXA', 2);


INSERT INTO PRODUTOS (CODIGO_PRODUTO, DESCRICAO_PRODUTO, ID_FORNECEDOR, ID_VENDEDOR)
VALUES
('P001', 'PÃO FRANCÊS', 1, 2),
('P002', 'CROISSANT', 1, 3),
('P003', 'BOLO DE CHOCOLATE', 2, 2),
('P004', 'CAFÉ EXPRESSO', 3, 1);

UPDATE PRODUTOS
SET ID_FORNECEDOR = 2
WHERE CODIGO_PRODUTO = 'P002';

DELETE FROM PRODUTOS
WHERE CODIGO_PRODUTO = 'P003';

SELECT * FROM PRODUTOS;
