CREATE DATABASE ABD_03361_A_FABIANE_AGUILERA;


USE ABD_03361_A_FABIANE_AGUILERA;

CREATE TABLE FAMILIA (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    PARENTESCO VARCHAR(50) NOT NULL,
    IDADE INT,
    CIDADE VARCHAR(50)
);

INSERT INTO FAMILIA (NOME, PARENTESCO, IDADE, CIDADE) VALUES ( 'Mário', 'pai','74','SÃO PAULO'); 
INSERT INTO FAMILIA (NOME, PARENTESCO, IDADE, CIDADE) VALUES ( 'Arineide', 'mãe','75','SÃO PAULO');
INSERT INTO FAMILIA (NOME, PARENTESCO, IDADE, CIDADE) VALUES ( 'Edson', 'esposo','54','SÃO PAULO'); 
INSERT INTO FAMILIA (NOME, PARENTESCO, IDADE, CIDADE) VALUES ( 'Fernanda', 'filha','17','SÃO PAULO'); 
INSERT INTO FAMILIA (NOME, PARENTESCO, IDADE, CIDADE) VALUES ( 'Marcelo', 'irmão','53','SÃO PAULO'); 