

-- BANCO DE EXEMPLO PARA _ABD_03361_A_NOME_RELATÓRIO_DE_VENDAS
 
-- TABELAS: CLIENTES E PEDIDOS
 
-- 1 CRIAR BASE DE DADOS CHAMADA RELATORIO_VENDAS_EMPRESA
 
CREATE DATABASE ABD_03361_A_FABIANE_AGUILERA_RELATORIO_VENDAS_EMPRESA;
USE ABD_03361_A_FABIANE_AGUILERA_RELATORIO_VENDAS_EMPRESA;

 
-- 2 CRIAR TABELA CLIENTES
-- CAMPOS: id, nome, cidade

CREATE TABLE CLIENTES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100),
    CIDADE VARCHAR(100)
);
 
-- 3 CRIAR TABELA PEDIDOS
-- CAMPOS: id, id_cliente, produto, quantidade, valor_unitario
-- LIGAR A COLUNA id_cliente À TABELA CLIENTES

CREATE TABLE PEDIDOS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_CLIENTE INT,
    PRODUTO VARCHAR(100),
    QUANTIDADE INT,
    VALOR_UNITARIO DECIMAL(10,2),
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID)
);

 
-- 4 INSERIR DADOS NAS TABELAS
-- CLIENTES: 300 REGISTROS
-- PEDIDOS: 300 REGISTROS, RELACIONANDO COM CLIENTES

CREATE PROCEDURE INSERIR_CLIENTES()
BEGIN
    DECLARE I INT DEFAULT 1;
    WHILE I <= 300 DO
        INSERT INTO CLIENTES (NOME, CIDADE)
        VALUES (CONCAT('CLIENTE_', I), CONCAT('CIDADE_', I));
        SET I = I + 1;
    END WHILE;
END;



CALL INSERIR_CLIENTES();




CREATE PROCEDURE INSERIR_PEDIDOS()
BEGIN
    DECLARE I INT DEFAULT 1;
    WHILE I <= 300 DO
        INSERT INTO PEDIDOS (ID_CLIENTE, PRODUTO, QUANTIDADE, VALOR_UNITARIO)
        VALUES (
            I, 
            CONCAT('PRODUTO_', I),
            FLOOR(1 + (RAND() * 10)),        -- Quantidade de 1 a 10
            ROUND(50 + (RAND() * 4950), 2)   -- Valor entre 50 e 5000
        );
        SET I = I + 1;
    END WHILE;
END;



CALL INSERIR_PEDIDOS();


SELECT COUNT(*) AS TOTAL_CLIENTES FROM CLIENTES;
SELECT COUNT(*) AS TOTAL_PEDIDOS FROM PEDIDOS;


 
-- 5 INNER JOIN
-- MOSTRAR APENAS CLIENTES QUE TÊM PEDIDOS
-- EXIBIR: NOME DO CLIENTE E PRODUTO

SELECT C.NOME AS NOME_CLIENTE, P.PRODUTO
FROM CLIENTES C
INNER JOIN PEDIDOS P ON C.ID = P.ID_CLIENTE;


-- 6 LEFT JOIN
-- MOSTRAR TODOS OS CLIENTES, MESMO QUE NÃO TENHAM PEDIDOS
-- EXIBIR: NOME DO CLIENTE E PRODUTO
 
SELECT 
    C.NOME AS NOME_CLIENTE,
    P.PRODUTO
FROM CLIENTES C
LEFT JOIN PEDIDOS P ON C.ID = P.ID_CLIENTE;

-- 7 RIGHT JOIN
-- MOSTRAR TODOS OS PEDIDOS, MESMO QUE NÃO TENHAM CLIENTE ASSOCIADO
-- EXIBIR: NOME DO CLIENTE E PRODUTO

SELECT 
    C.NOME AS NOME_CLIENTE,
    P.PRODUTO
FROM CLIENTES C
RIGHT JOIN PEDIDOS P ON C.ID = P.ID_CLIENTE;
 
-- 8 FULL JOIN
-- MOSTRAR TODOS OS CLIENTES E TODOS OS PEDIDOS, MESMO SEM CORRESPONDÊNCIA
-- DICA: NO MYSQL PODE SER FEITO COM UNION DE LEFT JOIN E RIGHT JOIN
 
SELECT 
    C.NOME AS NOME_CLIENTE,
    P.PRODUTO
FROM CLIENTES C
LEFT JOIN PEDIDOS P ON C.ID = P.ID_CLIENTE

UNION

SELECT 
    C.NOME AS NOME_CLIENTE,
    P.PRODUTO
FROM CLIENTES C
RIGHT JOIN PEDIDOS P ON C.ID = P.ID_CLIENTE;

-- 9 CROSS JOIN
-- COMBINAR TODOS OS CLIENTES COM TODOS OS PEDIDOS (PRODUTO CARTESIANO)
-- EXIBIR: NOME DO CLIENTE E PRODUTO

SELECT 
    C.NOME AS NOME_CLIENTE,
    P.PRODUTO
FROM CLIENTES C
CROSS JOIN PEDIDOS P;