USE ADB_03361_A_PEDRO_KLEIZ;

SELECT * FROM FAMILIA WHERE IDADE > 35;

SELECT * FROM FAMILIA WHERE CIDADE LIKE 'SÃO PAULO';

SELECT * FROM FAMILIA WHERE IDADE between 18 AND 20;


SELECT NOME FROM FAMILIA WHERE IDADE >= 22;

SELECT NOME, IDADE FROM FAMILIA WHERE IDADE < 18 ORDER BY IDADE ASC;

SELECT * FROM FAMILIA WHERE CIDADE IN ('SÃO PAULO' , 'RIO DE JANEIRO') ORDER BY NOME ASC;

-- NOME E IDADE DE PESSOAS QUE O NOME SEJA MAIOR QUE 15 E QUE A CIDADE SEJA SÃO PAULO EM ORDEM ASC

SELECT NOME, IDADE FROM FAMILIA WHERE LENGTH(NOME) > 5 AND CIDADE = ' SÃO PAULO' ORDER BY IDADE ASC;










