-- 1 UTILIZAR A BASE DE DADOS COM O NOME DE VOCÊS SEM _

USE ABD_03361_A_FABIANE_AGUILERA;
 
-- 2 CRIAR A TABELA DE CLIENTES_BANCO_ITAU
-- CAMPOS:
-- ID_CLIENTE (INT AUTO_INCREMENT, PRIMARY KEY)
-- NOME_CLIENTE (VARCHAR 100)
-- CPF (VARCHAR 11)

CREATE TABLE CLIENTES_BANCO_ITAU (
    ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
    NOME_CLIENTE VARCHAR(100),
    CPF VARCHAR(11)
);
 
-- 3 CRIAR A TABELA DE CONTAS
-- CAMPOS:
-- ID_CONTA (INT AUTO_INCREMENT, PRIMARY KEY)
-- ID_CLIENTE (INT, FK)
-- SALDO (DECIMAL 10,2)
-- TIPO_CONTA (VARCHAR 20)

CREATE TABLE CONTAS (
	ID_CONTA INT AUTO_INCREMENT PRIMARY KEY,
    ID_CLIENTE INT,
    SALDO DECIMAL(10,2),
    TIPO_CONTA VARCHAR(20),
	FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES_BANCO_ITAU(ID_CLIENTE)
    );
    
    
    
 
-- 4 POPULAR A TABELA CLIENTES COM 5 CLIENTES SEM DEFINIR AS COLUNAS

INSERT INTO CLIENTES_BANCO_ITAU
VALUES 
(NULL, 'João Silva', '12345678901'),
(NULL, 'Pedro Lima', '23456789012'),
(NULL, 'Maria Souza', '34567890123'),
(NULL, 'Ana Costa', '45678901234'),
(NULL, 'Carlos Pereira', '56789012345');
 
-- 5 POPULAR A TABELA CONTAS COM 5 CONTAS

INSERT INTO CONTAS
VALUES
(NULL, 1, 1000.00, 'Corrente'),
(NULL, 2, 500.00, 'Corrente'),
(NULL, 3, 800.00, 'Poupança'),
(NULL, 4, 1200.00, 'Corrente'),
(NULL, 5, 300.00, 'Poupança');
 
-- 6 EXERCÍCIO DE TRANSACÇÃO COM RELAÇÃO ENTRE CLIENTES E CONTAS
-- SITUAÇÃO: QUEREMOS TRANSFERIR 600 REAIS DE JOÃO SILVA PARA PEDRO LIMA
-- PASSO 1: INICIAR A TRANSACAO (BEGIN)
-- PASSO 2: DIMINUIR SALDO DE JOÃO SILVA
-- PASSO 3: AUMENTAR SALDO DE PEDRO LIMA
-- PASSO 4: SE SALDO DE JOÃO FICAR NEGATIVO, FAZER ROLLBACK, SENÃO COMMIT


-- 1 VERSÃO MAIS SIMPLES:

-- START TRANSACTION;

-- UPDATE CONTAS SET SALDO = SALDO - 600 WHERE ID_CLIENTE = 1;
-- UPDATE CONTAS SET SALDO = SALDO + 600 WHERE ID_CLIENTE = 2;

-- VERIFICAR SALDO DE JOÃO SILVA
-- SELECT SALDO INTO @SALDO_JOAO FROM CONTAS WHERE ID_CLIENTE = 1;

-- MOSTRAR SALDO PARA DECISÃO MANUAL
-- SELECT @SALDO_JOAO AS SALDO_DE_JOAO;

-- SE O SALDO FICAR NEGATIVO, DIGITE:
-- ROLLBACK;
-- SENÃO, DIGITE:
-- COMMIT;

-- 2 VERSÃO:

DELIMITER $$

CREATE PROCEDURE SP_TRANSFERIR(
    IN P_ID_ORIGEM INT,
    IN P_ID_DESTINO INT,
    IN P_VALOR DECIMAL(10,2)
)
BEGIN
    DECLARE SALDO_ORIGEM DECIMAL(10,2);

    -- Inicia a transação
    START TRANSACTION;

    -- Diminui o saldo do cliente de origem
    UPDATE CONTAS
    SET SALDO = SALDO - P_VALOR
    WHERE ID_CLIENTE = P_ID_ORIGEM;

    -- Aumenta o saldo do cliente de destino
    UPDATE CONTAS
    SET SALDO = SALDO + P_VALOR
    WHERE ID_CLIENTE = P_ID_DESTINO;

    -- Guarda o saldo atualizado do cliente de origem
    SELECT SALDO INTO SALDO_ORIGEM
    FROM CONTAS
    WHERE ID_CLIENTE = P_ID_ORIGEM;

    -- Verifica se o saldo ficou negativo
    IF SALDO_ORIGEM < 0 THEN
        ROLLBACK;
        SELECT 'SALDO INSUFICIENTE! TRANSFERÊNCIA CANCELADA.' AS MENSAGEM;
    ELSE
        COMMIT;
        SELECT 'TRANSFERÊNCIA REALIZADA COM SUCESSO!' AS MENSAGEM;
    END IF;

END $$

DELIMITER ;

-- Como executar
-- sql

CALL SP_TRANSFERIR(1, 2, 600);


SELECT 'TESTE';